name: Checks Builds on PR

on: [pull_request]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: build and publish
        run: |
          cd HideVolumeHidePlane
          dotnet restore HideVolumeHidePlane.csproj
          dotnet build HideVolumeHidePlane.csproj --configuration Release
